package elite.intel.gameapi;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import elite.intel.ai.mouth.subscribers.events.AiVoxResponseEvent;
import elite.intel.eventbus.GameEventBus;
import elite.intel.eventbus.UiBus;
import elite.intel.gameapi.journal.EventRegistry;
import elite.intel.gameapi.journal.events.BaseEvent;
import elite.intel.session.PlayerSession;
import elite.intel.tools.ws.WebSocketBroadcaster;
import elite.intel.ui.controller.ManagedService;
import elite.intel.ui.event.AppLogDebugEvent;
import elite.intel.util.json.GsonFactory;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.nio.file.*;
import java.util.List;
import java.util.concurrent.TimeUnit;

import static elite.intel.util.StringUtls.localizedSpeech;

/**
 * The JournalParser class is responsible for monitoring and parsing journal log files
 * generated by the Elite Dangerous game. It continuously watches a specified directory
 * for changes to log files, reads journal entries, processes event data, and publishes
 * events to the GameEventBus for further handling.
 * <p>
 * This class is implemented as a Runnable to allow asynchronous execution in a separate
 * thread. It uses a WatchService to detect file modifications or new files in the directory
 * and processes journal data incrementally. Parsing includes handling JSON-based event data
 * and publishing it to the event bus for downstream processing.
 * <p>
 * Key Features:
 * - Watches a specified directory for log file creation and modification.
 * - Reads and processes journal entries with support for handling UTF-8 BOM.
 * - Publishes parsed event objects to a central event bus for handling.
 * - Handles safe shutdown and interruption of the parser thread.
 * <p>
 * Threading Behavior:
 * - The class relies on a dedicated worker thread started via the start method.
 * - The stop method is used to request the thread to terminate, ensuring a clean shutdown.
 * <p>
 * Error Handling:
 * - Catches and logs exceptions such as I/O issues or unexpected parsing errors.
 * - Publishes error-related events (e.g., AppLogEvent) to notify other components.
 */
public class JournalParser implements Runnable, ManagedService {
    private static final Logger log = LogManager.getLogger(JournalParser.class);
    /**
     * How often the folder is re-listed for a newer journal by name. A directory listing is cheap, and a
     * game that has just opened a new journal writes its first lines within seconds anyway.
     */
    private static final long NEWEST_CHECK_INTERVAL_NANOS = TimeUnit.SECONDS.toNanos(5);
    private Path journalDir;
    private Thread processingThread;
    private volatile boolean isRunning;
    private final WebSocketBroadcaster webSocketBroadcaster = WebSocketBroadcaster.getInstance();

    public JournalParser() {
    }

    public synchronized void start() {
        journalDir = PlayerSession.getInstance().getJournalPath();
        if (processingThread != null && processingThread.isAlive()) {
            log.warn("JournalParser is already running");
            return;
        }
        isRunning = true;
        processingThread = new Thread(this, "JournalParserThread");
        processingThread.start();
        log.info("JournalParser started");
    }

    public synchronized void stop() {
        if (processingThread == null || !processingThread.isAlive()) {
            log.warn("JournalParser is not running");
            return;
        }
        isRunning = false;
        processingThread.interrupt();
        try {
            processingThread.join(5000); // Wait up to 5 seconds for clean shutdown
            log.info("JournalParser stopped");
        } catch (InterruptedException e) {
            log.warn("Interrupted while waiting for JournalParser to stop");
            Thread.currentThread().interrupt(); // Restore interrupted status
        }
        processingThread = null;
    }

    @Override
    public void run() {
        try {
            startReading();
        } catch (IOException e) {
            log.error("IOException in JournalParser", e);
            UiBus.publish(new AppLogDebugEvent("Please check journal directory"));
        } catch (InterruptedException e) {
            log.info("JournalParser interrupted, shutting down");
            Thread.currentThread().interrupt(); // Restore interrupted status
        } catch (Exception e) {
            log.error("Unexpected error in JournalParser", e);
            UiBus.publish(new AppLogDebugEvent("Please check journal directory"));
        }
    }

    private void startReading() throws IOException, InterruptedException {
        log.info("Starting Journal Parser");

        DataDirectoryValidator.validateAndWarn(journalDir, DataDirectoryValidator.DirectoryKind.JOURNAL);

        try (WatchService watchService = FileSystems.getDefault().newWatchService()) {
            journalDir.register(watchService, StandardWatchEventKinds.ENTRY_MODIFY, StandardWatchEventKinds.ENTRY_CREATE);

            // If the app is started before the game, no journal exists yet. Wait for one.
            Path currentFile = null;
            boolean journalWarningSpoken = false;
            while (isRunning && currentFile == null) {
                try {
                    currentFile = getLatestJournalFile();
                } catch (IOException e) {
                    if (!journalWarningSpoken) {
                        log.info("No journal file found yet - waiting for game to start...");
                        GameEventBus.publish(new AiVoxResponseEvent(localizedSpeech("speech.warning.noGameSession")));
                        journalWarningSpoken = true;
                    }
                    Thread.sleep(2000);
                }
            }
            if (!isRunning) return;
            long lastPosition = 0;
            log.info("Monitoring {}", currentFile.getFileName());
            long lastNewestCheck = System.nanoTime();

            while (isRunning) {
                Thread.sleep(200);

                if (Thread.currentThread().isInterrupted() || !isRunning) {
                    log.info("Shutting down JournalParser due to interruption or stop signal");
                    return;
                }

                // Fix for Windows (two bugs, same root cause: OS-cached directory-entry metadata)
                //
                // Bug 1 (fixed earlier): channel.size() returned a stale cached file size, so the
                //   read was gated behind a check that never became true. Fixed by reading directly.
                //
                // Bug 2 (this fix): File.lastModified() in getLatestJournalFile() returns stale
                //   cached values for a file being written by another process. Calling it on every
                //   poll caused the parser to switch to an older journal file (whose cached mtime
                //   appeared newer), reset lastPosition to 0, and read only expired events forever.
                //
                // Solution: never choose a file by mtime. The startup pick and the periodic re-check
                // below both go by the start stamp in the file's NAME (see JournalFiles), which the
                // filesystem cannot get stale; ENTRY_CREATE from the WatchService is kept as the fast
                // path for the moment the game opens a new journal.
                WatchKey key = watchService.poll();
                if (key != null) {
                    for (WatchEvent<?> watchEvent : key.pollEvents()) {
                        if (watchEvent.kind() == StandardWatchEventKinds.ENTRY_CREATE) {
                            @SuppressWarnings("unchecked")
                            Path created = ((WatchEvent<Path>) watchEvent).context();
                            if (JournalFiles.startStamp(created).isPresent()) {
                                lastPosition = 0;
                                currentFile = journalDir.resolve(created);
                                lastNewestCheck = System.nanoTime();
                                log.info("Switched to new journal file: {}", currentFile.getFileName());
                            }
                        }
                    }
                    key.reset();
                }
                // Backstop for a missed or never-delivered ENTRY_CREATE: one directory listing every few
                // seconds, by name. Cheap, and the only way a session that began on the wrong file (or
                // whose watch key went quiet) ever finds the file the game is actually writing.
                if (System.nanoTime() - lastNewestCheck >= NEWEST_CHECK_INTERVAL_NANOS) {
                    lastNewestCheck = System.nanoTime();
                    Path newest = newestJournalOrNull();
                    if (newest != null && !newest.equals(currentFile)) {
                        lastPosition = 0;
                        currentFile = newest;
                        log.info("Switched to newer journal file by name: {}", currentFile.getFileName());
                    }
                }

                try {
                    // JournalLineReader handles lines larger than its read buffer (e.g. a
                    // fleet-carrier StoredModules event over 64 KB), multi-byte UTF-8 across
                    // buffer boundaries, \r\n, the leading BOM, and partial trailing lines. It
                    // does NOT gate on channel.size() (stale on Windows) \u2014 see that class.
                    JournalLineReader reader = new JournalLineReader(currentFile, lastPosition);
                    List<String> lines = reader.readNewLines();
                    lastPosition = reader.getPosition();
                    log.debug("poll: file={} pos={} lines={}", currentFile.getFileName(), lastPosition, lines.size());

                    for (String line : lines) {
                        try {
                            String sanitizedLine = line.replaceAll("[\\p{Cntrl}\\p{Cc}\\p{Cf}]", "").trim();
                            if (!sanitizedLine.startsWith("{") || !sanitizedLine.endsWith("}")) continue;

                            JsonElement element = GsonFactory.getGson().fromJson(sanitizedLine, JsonElement.class);
                            if (!element.isJsonObject()) continue;

                            JsonObject eventJson = element.getAsJsonObject();
                            if (eventJson.has("event")) {
                                String eventType = eventJson.get("event").getAsString();
                                BaseEvent event = EventRegistry.createEvent(eventType, eventJson);
                                if (event != null && !event.isReplay() && !event.isExpired()) {
                                    GameEventBus.publish(event);
                                    webSocketBroadcaster.broadcast(event.toJson());
                                    UiBus.publish(new AppLogDebugEvent("\tProcessing Event: " + eventType));
                                    // debug, not info: this fires per event, and the logger is at info so the
                                    // edge-triggered lines above (file chosen, file switched) reach a bundle.
                                    log.debug("Processing Journal Event: {} {}", eventType, event.toJsonObject());
                                } else if (event != null && event.isReplay()) {
                                    log.debug("Skipping replay event: {}", eventType);
                                } else if (event != null && event.isExpired()) {
                                    log.warn("Skipping event: {}, reason {}", eventType, "Event expired");
                                }
                            }
                        } catch (Exception e) {
                            log.warn("Skipping malformed journal line: {} - {}", line, e.getMessage());
                        }
                    }
                } catch (IOException e) {
                    GameEventBus.publish(new AiVoxResponseEvent(localizedSpeech("speech.warning.journalReadError", e.getMessage())));
                    log.error("Error reading journal: {}", e.getMessage(), e);
                }

            }
        }
    }

    private Path getLatestJournalFile() throws IOException {
        return JournalFiles.newest(journalDir)
                .orElseThrow(() -> new IOException("No journal files found in " + journalDir));
    }

    /**
     * The newest journal by name, or null when the folder cannot be listed right now - a transient the
     * next check will retry, not a reason to stop tailing the file we have.
     */
    private Path newestJournalOrNull() {
        try {
            return JournalFiles.newest(journalDir).orElse(null);
        } catch (IOException e) {
            log.debug("Could not list {} for a newer journal: {}", journalDir, e.getMessage());
            return null;
        }
    }
}