package elite.intel.ai.hands;

/**
 * Represents the available actions and their associated game commands for
 * the in-game control system. The class helps in mapping specific actions
 * to their respective commands, which are linked with identifiers and
 * associated classes for controlling the game behavior.
 */
public class Bindings {
    /**
     * Enumeration representing various game commands and their associated attributes.
     * Each game command is linked with a binding name, an action, and a controller class.
     * This enum is used to map specific in-game actions to identifiers for processing and handling user inputs.
     */
    public enum GameCommand {

        BINDING_UIFOCUS("UIFocus"),

        /// ------------------------------------------------------------------------------------------------------------
        /// mappings for customCommands
        BINDING_TOGGLE_CARGO_SCOOP("ToggleCargoScoop"),
        BINDING_TOGGLE_CARGO_SCOOP_BUGGY("ToggleCargoScoop_Buggy"),
        BINDING_HARDPOINTS_TOGGLE("DeployHardpointToggle"),
        BINDING_FOCUS_COMMS_PANEL("FocusCommsPanel"),
        BINDING_FOCUS_COMMS_PANEL_BUGGY("FocusCommsPanel_Buggy"),
        BINDING_FOCUS_LEFT_PANEL("FocusLeftPanel"),
        BINDING_FOCUS_CONTACTS_PANEL_BUGGY("FocusLeftPanel_Buggy"),
        BINDING_FOCUS_LEFT_PANEL_BUGGY("FocusLeftPanel_Buggy"),
        BINDING_FOCUS_INTERNAL_PANEL("FocusRightPanel"),
        BINDING_FOCUS_INTERNAL_PANEL_BUGGY("FocusRightPanel_Buggy"),
        BINDING_FOCUS_STATUS_PANEL("FocusRightPanel"),
        BINDING_FOCUS_STATUS_PANEL_BUGGY("FocusRightPanel_Buggy"),
        BINDING_FOCUS_ROLE_PANEL_BUGGY("FocusRadarPanel_Buggy"),
        BINDING_FOCUS_ROLE_PANEL("FocusRadarPanel"),
        BINDING_FOCUS_LOADOUT_PANEL_BUGGY("FocusRadarPanel_Buggy"),
        BINDING_LANDING_GEAR_TOGGLE("LandingGearToggle"),
        BINDING_RESET_POWER_DISTRIBUTION("ResetPowerDistribution"),
        BINDING_RESET_POWER_DISTRIBUTION_BUGGY("ResetPowerDistribution_Buggy"),

        BINDING_INCREASE_ENGINES_POWER("IncreaseEnginesPower"),
        BINDING_INCREASE_SYSTEMS_POWER("IncreaseSystemsPower"),
        BINDING_INCREASE_SHIELDS_POWER("IncreaseSystemsPower"),
        BINDING_INCREASE_WEAPONS_POWER("IncreaseWeaponsPower"),

        BINDING_INCREASE_ENGINES_POWER_BUGGY("IncreaseEnginesPower_Buggy"),
        BINDING_INCREASE_SYSTEMS_POWER_BUGGY("IncreaseSystemsPower_Buggy"),
        BINDING_INCREASE_SHIELDS_POWER_BUGGY("IncreaseSystemsPower_Buggy"),
        BINDING_INCREASE_WEAPONS_POWER_BUGGY("IncreaseWeaponsPower_Buggy"),

        BINDING_GALAXY_MAP("GalaxyMapOpen"),
        BINDING_GALAXY_MAP_BUGGY("GalaxyMapOpen_Buggy"),
        BINDING_GALAXY_MAP_HUMANOID("GalaxyMapOpen_Humanoid"),

        BINDING_LOCAL_MAP("SystemMapOpen"),
        BINDING_LOCAL_MAP_BUGGY("SystemMapOpen_Buggy"),
        BINDING_SYSTEM_MAP_HUMANOID("SystemMapOpen_Humanoid"),

        BINDING_EXPLORATION_FSSDISCOVERY_SCAN("ExplorationFSSEnter"),

        BINDING_CAM_ZOOM_IN("CamZoomIn"),
        BINDING_CAM_ZOOM_OUT("CamZoomOut"),
        BINDING_EXIT_KEY("UI_Back"),
        BINDING_UI_DOWN("UI_Down"),
        BINDING_UI_LEFT("UI_Left"),
        BINDING_UI_RIGHT("UI_Right"),
        BINDING_UI_SELECT("UI_Select"),
        BINDING_UI_TOGGLE("UI_Toggle"),
        BINDING_UI_UP("UI_Up"),

        BINDING_EXIT_SUPERCRUISE("Supercruise"),
        BINDING_JUMP_TO_HYPERSPACE("Hyperspace"),
        BINDING_ENTER_SUPERCRUISE("Supercruise"),


        //TODO: convert to custom
        BINDING_ACTIVATE_ANALYSIS_MODE("PlayerHUDModeToggle"),
        BINDING_ACTIVATE_ANALYSIS_MODE_BUGGY("PlayerHUDModeToggle_Buggy"),
        BINDING_ACTIVATE_COMBAT_MODE("PlayerHUDModeToggle"),
        BINDING_ACTIVATE_COMBAT_MODE_BUGGY("PlayerHUDModeToggle_Buggy"),


        /// ------------------------------------------------------------------------------------------------------------
        /// basic commands
        BINDING_ACTIVATE("UI_Select"),
        BINDING_NIGHT_VISION_TOGGLE("NightVisionToggle"),
        BINDING_CYCLE_NEXT_PAGE("CycleNextPage"),
        BINDING_CYCLE_NEXT_PANEL("CycleNextPanel"),
        BINDING_CYCLE_PREVIOUS_PAGE("CyclePreviousPage"),
        BINDING_CYCLE_PREVIOUS_PANEL("CyclePreviousPanel"),
        BINDING_HEAD_LOOK_RESET("HeadLookReset"),

        BINDING_CYCLE_NEXT_SUBSYSTEM("CycleNextSubsystem"),
        BINDING_CYCLE_PREVIOUS_SUBSYSTEM("CyclePreviousSubsystem"),

        BINDING_DEPLOY_HEAT_SINK("DeployHeatSink"),
        BINDING_USE_SHIELD_CELL("UseShieldCell"),
        BINDING_FIRE_CHAFF_LAUNCHER("FireChaffLauncher"),
        BINDING_DRIVE_ASSIST("ToggleDriveAssist"),
        BINDING_EXPLORATION_FSSQUIT("ExplorationFSSQuit"),

        EXPLORATION_SAAEXIT_THIRD_PERSON("ExplorationSAAExitThirdPerson"),

        BINDING_RADAR_DECREASE_RANGE("RadarDecreaseRange"),
        BINDING_RADAR_INCREASE_RANGE("RadarIncreaseRange"),

        BINDING_RECALL_DISMISS_SHIP("RecallDismissShip"),

        BINDING_REQUEST_DEFENSIVE_BEHAVIOUR("OrderDefensiveBehaviour"),
        BINDING_REQUEST_FOCUS_TARGET("OrderFocusTarget"),
        BINDING_REQUEST_HOLD_FIRE("OrderHoldFire"),
        BINDING_REQUEST_REQUEST_DOCK("OrderRequestDock"),
        OPEN_ORDERS("OpenOrders"),

        BINDING_SELECT_TARGETS_TARGET("SelectTargetsTarget"),

        BINDING_PLANETARY_APPROACH_SPEED75("SetSpeed25"),
        BINDING_SET_SPEED25("SetSpeed25"),
        BINDING_SET_SPEED50("SetSpeed50"),
        BINDING_SET_SPEED75("SetSpeed75"),
        BINDING_SET_OPTIMAL_SPEED("SetSpeed75"),
        BINDING_SET_SPEED100("SetSpeed100"),
        BINDING_SET_SPEED_ZERO("SetSpeedZero"),
        BINDING_INCREASE_SPEED("ForwardKey"),
        BINDING_DECREASE_SPEED("BackwardKey"),

        BINDING_SHIP_LIGHTS_TOGGLE("ShipSpotLightToggle"),
        BINDING_BUGGY_LIGHTS_TOGGLE("HeadlightsBuggyButton"),


        BINDING_SELECT_HIGHEST_THREAT("SelectHighestThreat"),

        BINDING_TARGET_NEXT_ROUTE_SYSTEM("TargetNextRouteSystem"),
        BINDING_ON_FOOT_WHEEL("HumanoidOpenAccessPanelButton"),
        BINDING_TARGET_WINGMAN0("TargetWingman0"),
        BINDING_TARGET_WINGMAN1("TargetWingman1"),
        BINDING_TARGET_WINGMAN2("TargetWingman2"),
        BINDING_WING_NAV_LOCK("WingNavLock"),

        /// These two trigger must operate only in analysis mode for safety - hands off the trigger!
        BINDING_PRIMARY_FIRE("PrimaryFire"),
        BINDING_SECONDARY_FIRE("SecondaryFire"),
        BINDING_CYCLE_NEXT_FIRE_GROUP("CycleFireGroupNext"),


        AUTO_BREAK_BUGGY_BUTTON("AutoBreakBuggyButton"),
        BACKWARD_KEY("BackwardKey"),
        CAM_TRANSLATE_BACKWARD("CamTranslateBackward"),
        CAM_TRANSLATE_DOWN("CamTranslateDown"),
        CAM_TRANSLATE_FORWARD("CamTranslateForward"),
        CAM_TRANSLATE_LEFT("CamTranslateLeft"),
        CAM_TRANSLATE_RIGHT("CamTranslateRight"),
        CAM_TRANSLATE_UP("CamTranslateUp"),
        CAM_YAW_RIGHT("CamYawRight"),
        CAM_ZOOM_IN("CamZoomIn"),
        CAM_ZOOM_OUT("CamZoomOut"),
        CHANGE_CONSTRUCTION_OPTION("ChangeConstructionOption"),
        CYCLE_FIRE_GROUP_NEXT("CycleFireGroupNext"),
        CYCLE_NEXT_PAGE("CycleNextPage"),
        CYCLE_NEXT_PANEL("CycleNextPanel"),
        CYCLE_NEXT_SUBSYSTEM("CycleNextSubsystem"),
        CYCLE_PREVIOUS_PAGE("CyclePreviousPage"),
        CYCLE_PREVIOUS_PANEL("CyclePreviousPanel"),
        CYCLE_PREVIOUS_SUBSYSTEM("CyclePreviousSubsystem"),
        DEPLOY_HARDPOINT_TOGGLE("DeployHardpointToggle"),
        DEPLOY_HEAT_SINK("DeployHeatSink"),
        DOWN_THRUST_BUTTON("DownThrustButton"),
        EJECT_ALL_CARGO("EjectAllCargo"),
        EXIT_SETTLEMENT_PLACEMENT_CAMERA("ExitSettlementPlacementCamera"),
        EXPLORATION_FSSDISCOVERY_SCAN("ExplorationFSSDiscoveryScan"),
        EXPLORATION_FSSENTER("ExplorationFSSEnter"),
        EXPLORATION_FSSQUIT("ExplorationFSSQuit"),
        EXPLORATION_SAACHANGE_SCANNED_AREA_VIEW_TOGGLE("ExplorationSAAChangeScannedAreaViewToggle"),
        FSTOP_DEC("FStopDec"),
        FSTOP_INC("FStopInc"),
        FIRE_CHAFF_LAUNCHER("FireChaffLauncher"),
        FIX_CAMERA_RELATIVE_TOGGLE("FixCameraRelativeToggle"),
        FIX_CAMERA_WORLD_TOGGLE("FixCameraWorldToggle"),
        FOCUS_COMMS_PANEL("FocusCommsPanel"),
        FOCUS_COMMS_PANEL_BUGGY("FocusCommsPanel_Buggy"),
        FOCUS_COMMS_PANEL_HUMANOID("FocusCommsPanel_Humanoid"),
        FOCUS_LEFT_PANEL("FocusLeftPanel"),
        FOCUS_LEFT_PANEL_BUGGY("FocusLeftPanel_Buggy"),
        FOCUS_RADAR_PANEL("FocusRadarPanel"),
        FOCUS_RADAR_PANEL_BUGGY("FocusRadarPanel_Buggy"),
        FOCUS_RIGHT_PANEL("FocusRightPanel"),
        FOCUS_RIGHT_PANEL_BUGGY("FocusRightPanel_Buggy"),
        FORWARD_KEY("ForwardKey"),
        FREE_CAM_SPEED_DEC("FreeCamSpeedDec"),
        FREE_CAM_SPEED_INC("FreeCamSpeedInc"),
        FREE_CAM_HUD("FreeCamToggleHUD"),
        GALAXY_MAP_HOME("GalaxyMapHome"),
        GALAXY_MAP("GalaxyMapOpen"),
        GALAXY_MAP_BUGGY("GalaxyMapOpen_Buggy"),
        GALAXY_MAP_HUMANOID("GalaxyMapOpen_Humanoid"),
        GALNET_AUDIO_CLEAR_QUEUE("GalnetAudio_ClearQueue"),
        GALNET_AUDIO_PLAY_PAUSE("GalnetAudio_Play_Pause"),
        GALNET_AUDIO_SKIP_BACKWARD("GalnetAudio_SkipBackward"),
        GALNET_AUDIO_SKIP_FORWARD("GalnetAudio_SkipForward"),
        HEAD_LOOK_RESET("HeadLookReset"),
        HEADLIGHTS_BUGGY_BUTTON("HeadlightsBuggyButton"),
        HUMANOID_BACKWARD_BUTTON("HumanoidBackwardButton"),
        HUMANOID_BATTERY("HumanoidBattery"),
        HUMANOID_CLEAR_AUTHORITY_LEVEL("HumanoidClearAuthorityLevel"),
        HUMANOID_CONFLICT_CONTEXTUAL_UIBUTTON("HumanoidConflictContextualUIButton"),
        HUMANOID_CROUCH_BUTTON("HumanoidCrouchButton"),
        HUMANOID_EMOTE_SLOT1("HumanoidEmoteSlot1"),
        HUMANOID_EMOTE_SLOT2("HumanoidEmoteSlot2"),
        HUMANOID_EMOTE_SLOT3("HumanoidEmoteSlot3"),
        HUMANOID_EMOTE_SLOT4("HumanoidEmoteSlot4"),
        HUMANOID_EMOTE_SLOT5("HumanoidEmoteSlot5"),
        HUMANOID_EMOTE_SLOT6("HumanoidEmoteSlot6"),
        HUMANOID_EMOTE_SLOT7("HumanoidEmoteSlot7"),
        HUMANOID_EMOTE_SLOT8("HumanoidEmoteSlot8"),
        HUMANOID_FORWARD_BUTTON("HumanoidForwardButton"),
        HUMANOID_HEALTH_PACK("HumanoidHealthPack"),
        HUMANOID_HIDE_WEAPON_BUTTON("HumanoidHideWeaponButton"),
        HUMANOID_ITEM_WHEEL_BUTTON("HumanoidItemWheelButton"),
        HUMANOID_ITEM_WHEEL_BUTTON_XLEFT("HumanoidItemWheelButton_XLeft"),
        HUMANOID_ITEM_WHEEL_BUTTON_XRIGHT("HumanoidItemWheelButton_XRight"),
        HUMANOID_ITEM_WHEEL_BUTTON_YDOWN("HumanoidItemWheelButton_YDown"),
        HUMANOID_ITEM_WHEEL_BUTTON_YUP("HumanoidItemWheelButton_YUp"),
        HUMANOID_JUMP_BUTTON("HumanoidJumpButton"),
        HUMANOID_MELEE_BUTTON("HumanoidMeleeButton"),
        HUMANOID_ACCESS_PANEL_BUTTON("HumanoidOpenAccessPanelButton"),
        HUMANOID_RELOAD_BUTTON("HumanoidReloadButton"),
        HUMANOID_SELECT_EMPGRENADE("HumanoidSelectEMPGrenade"),
        HUMANOID_SELECT_FRAG_GRENADE("HumanoidSelectFragGrenade"),
        HUMANOID_SELECT_PRIMARY_WEAPON_BUTTON("HumanoidSelectPrimaryWeaponButton"),
        HUMANOID_SELECT_SECONDARY_WEAPON_BUTTON("HumanoidSelectSecondaryWeaponButton"),
        HUMANOID_SELECT_SHIELD_GRENADE("HumanoidSelectShieldGrenade"),
        HUMANOID_SPRINT_BUTTON("HumanoidSprintButton"),
        HUMANOID_STRAFE_LEFT_BUTTON("HumanoidStrafeLeftButton"),
        HUMANOID_STRAFE_RIGHT_BUTTON("HumanoidStrafeRightButton"),
        HUMANOID_SWITCH_TO_COMP_ANALYSER("HumanoidSwitchToCompAnalyser"),
        HUMANOID_SWITCH_TO_RECHARGE_TOOL("HumanoidSwitchToRechargeTool"),
        HUMANOID_SWITCH_TO_SUIT_TOOL("HumanoidSwitchToSuitTool"),
        HUMANOID_SWITCH_WEAPON("HumanoidSwitchWeapon"),
        HUMANOID_THROW_GRENADE_BUTTON("HumanoidThrowGrenadeButton"),
        HUMANOID_FLASHLIGHT_BUTTON("HumanoidToggleFlashlightButton"),
        HUMANOID_MISSION_HELP_PANEL_BUTTON("HumanoidToggleMissionHelpPanelButton"),
        HUMANOID_NIGHT_VISION_BUTTON("HumanoidToggleNightVisionButton"),
        HUMANOID_SHIELDS_BUTTON("HumanoidToggleShieldsButton"),
        HUMANOID_UTILITY_WHEEL_CYCLE_MODE("HumanoidUtilityWheelCycleMode"),
        HUMANOID_WALK_BUTTON("HumanoidWalkButton"),
        HYPER_SUPER_COMBINATION("HyperSuperCombination"),
        JUMP_TO_HYPERSPACE("Hyperspace"),
        INCREASE_ENGINES_POWER("IncreaseEnginesPower"),
        INCREASE_ENGINES_POWER_BUGGY("IncreaseEnginesPower_Buggy"),
        INCREASE_SYSTEMS_POWER("IncreaseSystemsPower"),
        INCREASE_SYSTEMS_POWER_BUGGY("IncreaseSystemsPower_Buggy"),
        INCREASE_WEAPONS_POWER("IncreaseWeaponsPower"),
        INCREASE_WEAPONS_POWER_BUGGY("IncreaseWeaponsPower_Buggy"),
        LANDING_GEAR_TOGGLE("LandingGearToggle"),
        MOVE_FREE_CAM_BACKWARDS("MoveFreeCamBackwards"),
        MOVE_FREE_CAM_DOWN("MoveFreeCamDown"),
        MOVE_FREE_CAM_FORWARD("MoveFreeCamForward"),
        MOVE_FREE_CAM_LEFT("MoveFreeCamLeft"),
        MOVE_FREE_CAM_RIGHT("MoveFreeCamRight"),
        MOVE_FREE_CAM_UP("MoveFreeCamUp"),
        MOVE_PLACEMENT_CAM_BACKWARDS("MovePlacementCamBackwards"),
        MOVE_PLACEMENT_CAM_DOWN("MovePlacementCamDown"),
        MOVE_PLACEMENT_CAM_FORWARD("MovePlacementCamForward"),
        MOVE_PLACEMENT_CAM_LEFT("MovePlacementCamLeft"),
        MOVE_PLACEMENT_CAM_RIGHT("MovePlacementCamRight"),
        MOVE_PLACEMENT_CAM_UP("MovePlacementCamUp"),
        NIGHT_VISION_TOGGLE("NightVisionToggle"),
        OPEN_CODEX_GO_TO_DISCOVERY("OpenCodexGoToDiscovery"),
        OPEN_CODEX_GO_TO_DISCOVERY_BUGGY("OpenCodexGoToDiscovery_Buggy"),
        REQUEST_AGGRESSIVE_BEHAVIOUR("OrderAggressiveBehaviour"),
        REQUEST_DEFENSIVE_BEHAVIOUR("OrderDefensiveBehaviour"),
        REQUEST_FOCUS_TARGET("OrderFocusTarget"),
        REQUEST_FOLLOW("OrderFollow"),
        REQUEST_HOLD_FIRE("OrderHoldFire"),
        REQUEST_HOLD_POSITION("OrderHoldPosition"),
        REQUEST_REQUEST_DOCK("OrderRequestDock"),
        PAUSE("Pause"),
        PHOTO_CAMERA_TOGGLE("PhotoCameraToggle"),
        PHOTO_CAMERA_BUGGY("PhotoCameraToggle_Buggy"),
        PHOTO_CAMERA_HUMANOID("PhotoCameraToggle_Humanoid"),
        PLACEMENT_CAM_SPEED_DEC("PlacementCamSpeedDec"),
        PLACEMENT_CAM_SPEED_INC("PlacementCamSpeedInc"),
        PLAYER_HUDMODE_TOGGLE("PlayerHUDModeToggle"),
        PLAYER_HUDMODE_BUGGY("PlayerHUDModeToggle_Buggy"),
        PRIMARY_FIRE("PrimaryFire"),
        QUICK_COMMS_PANEL_BUGGY("QuickCommsPanel_Buggy"),
        QUICK_COMMS_PANEL_HUMANOID("QuickCommsPanel_Humanoid"),
        QUIT_CAMERA("QuitCamera"),
        RADAR_DECREASE_RANGE("RadarDecreaseRange"),
        RADAR_INCREASE_RANGE("RadarIncreaseRange"),
        RECALL_DISMISS_SHIP("RecallDismissShip"),
        RESET_POWER_DISTRIBUTION("ResetPowerDistribution"),
        RESET_POWER_DISTRIBUTION_BUGGY("ResetPowerDistribution_Buggy"),
        ROLL_LEFT_BUTTON("RollLeftButton"),
        ROLL_RIGHT_BUTTON("RollRightButton"),
        SECONDARY_FIRE("SecondaryFire"),
        SELECT_HIGHEST_THREAT("SelectHighestThreat"),
        SELECT_TARGETS_TARGET("SelectTargetsTarget"),
        SET_SPEED100("SetSpeed100"),
        SET_SPEED25("SetSpeed25"),
        SET_SPEED50("SetSpeed50"),
        SET_SPEED75("SetSpeed75"),
        SET_SPEED_ZERO("SetSpeedZero"),
        SHIP_SPOT_LIGHT_TOGGLE("ShipSpotLightToggle"),
        STORE_TOGGLE("StoreToggle"),
        ENTER_SUPERCRUISE("Supercruise"),
        SYSTEM_MAP("SystemMapOpen"),
        SYSTEM_MAP_BUGGY("SystemMapOpen_Buggy"),
        SYSTEM_MAP_HUMANOID("SystemMapOpen_Humanoid"),
        TARGET_NEXT_ROUTE_SYSTEM("TargetNextRouteSystem"),
        TARGET_WINGMAN0("TargetWingman0"),
        TARGET_WINGMAN1("TargetWingman1"),
        TARGET_WINGMAN2("TargetWingman2"),
        ADVANCE_MODE("ToggleAdvanceMode"),
        CARGO_SCOOP("ToggleCargoScoop"),
        CARGO_SCOOP_BUGGY("ToggleCargoScoop_Buggy"),
        DRIVE_ASSIST("ToggleDriveAssist"),
        FLIGHT_ASSIST("ToggleFlightAssist"),
        FREE_CAM("ToggleFreeCam"),
        ROTATION_LOCK("ToggleRotationLock"),
        UIFOCUS("UIFocus"),
        UI_BACK("UI_Back"),
        UI_DOWN("UI_Down"),
        UI_LEFT("UI_Left"),
        UI_RIGHT("UI_Right"),
        UI_SELECT("UI_Select"),
        UI_TOGGLE("UI_Toggle"),
        UI_UP("UI_Up"),
        UP_THRUST_BUTTON("UpThrustButton"),
        USE_SHIELD_CELL("UseShieldCell"),
        VANITY_CAMERA_EIGHT("VanityCameraEight"),
        VANITY_CAMERA_FIVE("VanityCameraFive"),
        VANITY_CAMERA_FOUR("VanityCameraFour"),
        VANITY_CAMERA_NINE("VanityCameraNine"),
        VANITY_CAMERA_ONE("VanityCameraOne"),
        VANITY_CAMERA_SCROLL_LEFT("VanityCameraScrollLeft"),
        VANITY_CAMERA_SCROLL_RIGHT("VanityCameraScrollRight"),
        VANITY_CAMERA_SEVEN("VanityCameraSeven"),
        VANITY_CAMERA_SIX("VanityCameraSix"),
        VANITY_CAMERA_THREE("VanityCameraThree"),
        VANITY_CAMERA_TWO("VanityCameraTwo"),
        WING_NAV_LOCK("WingNavLock")
        ;
        //UP_THRUST_BUTTON("up_thrust_button", "UpThrustButton",GenericGameController.class),
        //DOWN_THRUST_BUTTON("down_thrust_button", "DownThrustButton",GenericGameController.class);


        ///
        private final String gameBinding;

        GameCommand(String gameBinding) {
            this.gameBinding = gameBinding;
        }


        public String getGameBinding() {
            return gameBinding;
        }
    }
}