package elite.intel.companion.memory;

import elite.intel.companion.model.ConversationTopic;

import java.util.List;

/**
 * Cheap metadata snapshot for {@code PromptComposer} to render the memory indexes block, without
 * loading actual memory content. Hints are derived from static {@code ConversationTopic} descriptions plus this
 * metadata, never generated by the LLM.
 *
 * @param llmMemoryUsed      number of items currently in llm_memory
 * @param llmMemoryCapacity  maximum llm_memory items
 * @param topicsWithMemory   topics that currently have mid-term memory entries
 */
public record MemoryAvailabilitySnapshot(
        int llmMemoryUsed,
        int llmMemoryCapacity,
        List<ConversationTopic> topicsWithMemory
) {}
